version: "3"
services:
  webdictionary:
    image: opetstudio/erevna-dictionary-php:201710
    ports:
      - "4002:80"
    volumes:
      - ./log:/var/log/apache2
    environment:
      - PHP_ENV=production
      # - ./src:/var/www/src
    # web:
    #     build: .
    #     ports:
    #         - "8086:80"
    #     links:
    #         - app
    # app:
    #     build: .
    #     # ports:
    #     #     - ":9000"
    #
    #     # seems like fpm receives the full path from nginx
    #     # and tries to find the files in this dock, so it must
    #     # be the same as nginx.root
    #     volumes:
    #         - ./:/usr/src/app
#     web:
#         image: nginx:latest
#         ports:
#             - "8086:80"
#         volumes:
#             - ./src:/src
#             - ./site.conf:/etc/nginx/conf.d/default.conf
#         networks:
#             - code-network
#     php:
#         image: php:fpm
#         volumes:
#             - ./src:/src
#         networks:
#             - code-network
#
# networks:
#     code-network:
#         driver: bridge
